import type { MockUser } from './types';

const usersMock: MockUser[] = [
  {
    _id: '68a0fd52b981bde64c64efdc',
    username: 'PalleRotonde',
    email: 'godo.molto@example.com',
    choices: [
      {
        _id: '68a087e230bfb72e299e20cf',
        value: 'Il gruppo si divide',
        rarity: 'common',
        index: 0,
        occured: true,
      },
      {
        _id: '68a087e230bfb72e299e20c1',
        value: "Ordine eccessivo all'All you can eat!",
        rarity: 'uncommon',
        index: 0,
        occured: false,
      },
      {
        _id: '68a087e230bfb72e299e20cd',
        value: 'Dopo esserci accordati per un orario per trovarci, arriveremo in ritardo',
        rarity: 'uncommon',
        index: 0,
        occured: true,
      },
      {
        _id: '68a087e230bfb72e299e20dc',
        value: 'Mutande nel congelatore',
        rarity: 'uncommon',
        index: 0,
        occured: false,
      },
      {
        _id: '68a087e230bfb72e299e20c7',
        value: 'Qualcuno si farà male',
        rarity: 'uncommon',
        index: 0,
        occured: true,
      },
      {
        _id: '68a087e230bfb72e299e20c9',
        value: 'Qualche ragazzo (esterno a noi) ci proverà con una ragazza del gruppo',
        rarity: 'rare',
        index: 0,
        occured: false,
      },
      {
        _id: '68a087e230bfb72e299e20c8',
        value: "È l'ora dello sbusto",
        rarity: 'common',
        index: 0,
        occured: true,
      },
      {
        _id: '68a087e230bfb72e299e20ce',
        value: "Qualcuno si prende un'influenza/raffreddore",
        rarity: 'rare',
        index: 0,
        occured: false,
      },
      {
        _id: '68a087e230bfb72e299e20c6',
        value: "Il proprietario dell'appartamento verrà a lamentarsi",
        rarity: 'epic',
        index: 0,
        occured: false,
      },
    ],
  },
  {
    _id: '68a2f3498db1b82b6bdc1213',
    username: 't3ox',
    email: 'matteo.vattimo.mv@gmail.com',
    choices: [
      {
        _id: '68a087e230bfb72e299e20c8',
        value: "È l'ora dello sbusto",
        rarity: 'common',
        index: 0,
        occured: true,
      },
      {
        _id: '68a087e230bfb72e299e20cc',
        value: 'Qualcuno si brucia in spiaggia',
        rarity: 'common',
        index: 0,
        occured: false,
      },
      {
        _id: '68a0ed35cdbabd8515c243a1',
        value: 'Il sito si rompe',
        index: 0,
        occured: true,
        rarity: 'uncommon',
      },
      {
        _id: '68a087e230bfb72e299e20c9',
        value: 'Qualche ragazzo (esterno a noi) ci proverà con una ragazza del gruppo',
        rarity: 'rare',
        index: 0,
        occured: false,
      },
      {
        _id: '68a087e230bfb72e299e20ca',
        value: 'Litigio acceso e/o botte',
        rarity: 'epic',
        index: 0,
        occured: false,
      },
      {
        _id: '68a087e230bfb72e299e20c5',
        value: 'Avverrà un Threesome',
        rarity: 'epic',
        index: 0,
        occured: false,
      },
      {
        _id: '68a0b6453b093eb4dd3c98f3',
        value: 'Grande vincita al Bingo!',
        rarity: 'legendary',
        index: 0,
        occured: true,
      },
      {
        _id: '68a087e230bfb72e299e20c3',
        value: 'Teo e Diana dormiranno assieme',
        rarity: 'legendary',
        index: 0,
        occured: true,
      },
      {
        _id: '68a087e230bfb72e299e20c7',
        value: 'Qualcuno si farà male',
        rarity: 'uncommon',
        index: 0,
        occured: true,
      },
    ],
  },
  {
    _id: '68a2f3478db1b82b6bdc1212',
    username: 'ducafelino',
    email: 'stefano.fusco02@gmail.com',
    choices: [
      {
        _id: '68a087e230bfb72e299e20d5',
        value: 'Fugna fugna con cosplayer di Hatsune Miku',
        rarity: 'mythic',
        index: 0,
        occured: false,
      },
      {
        _id: '68a087e230bfb72e299e20c8',
        value: "È l'ora dello sbusto",
        rarity: 'common',
        index: 0,
        occured: true,
      },
      {
        _id: '68a087e230bfb72e299e20dc',
        value: 'Mutande nel congelatore',
        rarity: 'uncommon',
        index: 0,
        occured: false,
      },
      {
        _id: '68a0ed35cdbabd8515c243a1',
        value: 'Il sito si rompe',
        index: 0,
        occured: true,
        rarity: 'uncommon',
      },
      {
        _id: '68a087e230bfb72e299e20ce',
        value: "Qualcuno si prende un'influenza/raffreddore",
        rarity: 'rare',
        index: 0,
        occured: false,
      },
      {
        _id: '68a087e230bfb72e299e20d8',
        value: 'Qualcuno rompe qualcosa',
        rarity: 'epic',
        index: 0,
        occured: false,
      },
      {
        _id: '68a087e230bfb72e299e20ca',
        value: 'Litigio acceso e/o botte',
        rarity: 'epic',
        index: 0,
        occured: false,
      },
      {
        _id: '68a0b6453b093eb4dd3c98f3',
        value: 'Grande vincita al Bingo!',
        rarity: 'legendary',
        index: 0,
        occured: true,
      },
      {
        _id: '68a087e230bfb72e299e20c4',
        value: 'Cataclisma',
        rarity: 'legendary',
        index: 0,
        occured: false,
      },
    ],
  },
];

export default usersMock;
